import type { Employee, Suggestion, AdminUser } from './types';

// Sample employees data
export const sampleEmployees: Employee[] = [
  {
    id: 'emp001',
    name: 'Sarah Johnson',
    department: 'Engineering',
    riskLevel: 'high',
    jobTitle: 'Software Developer',
    workstation: 'Desk A-12',
    lastAssessment: '2024-01-15T10:30:00Z',
  },
  {
    id: 'emp002',
    name: 'Michael Chen',
    department: 'Marketing',
    riskLevel: 'medium',
    jobTitle: 'Marketing Manager',
    workstation: 'Desk B-05',
    lastAssessment: '2024-01-20T14:15:00Z',
  },
  {
    id: 'emp003',
    name: 'Emma Williams',
    department: 'HR',
    riskLevel: 'low',
    jobTitle: 'HR Coordinator',
    workstation: 'Desk C-08',
    lastAssessment: '2024-01-10T09:00:00Z',
  },
  {
    id: 'emp004',
    name: 'David Brown',
    department: 'Engineering',
    riskLevel: 'high',
    jobTitle: 'Senior Developer',
    workstation: 'Desk A-15',
    lastAssessment: '2024-01-18T11:45:00Z',
  },
  {
    id: 'emp005',
    name: 'Lisa Davis',
    department: 'Finance',
    riskLevel: 'medium',
    jobTitle: 'Financial Analyst',
    workstation: 'Desk D-03',
    lastAssessment: '2024-01-22T16:20:00Z',
  },
];

// Sample admin users
export const sampleAdminUsers: AdminUser[] = [
  {
    email: 'admin@company.com',
    name: 'Admin User',
    role: 'HR Manager',
    permissions: ['create_suggestions', 'update_status', 'view_all'],
  },
  {
    email: 'hr@company.com',
    name: 'HR Coordinator',
    role: 'HR Staff',
    permissions: ['update_status', 'view_all'],
  },
  {
    email: 'viewer@company.com',
    name: 'Viewer User',
    role: 'Viewer',
    permissions: ['view_all'],
  },
];

// Sample suggestions data
export const sampleSuggestions: Omit<Suggestion, 'id'>[] = [
  {
    employeeId: 'emp001',
    type: 'equipment',
    description: 'Adjustable standing desk recommended for prolonged sitting',
    status: 'pending',
    priority: 'high',
    source: 'vida',
    createdBy: 'vida-system',
    dateCreated: '2024-01-15T10:30:00Z',
    dateUpdated: '2024-01-15T10:30:00Z',
    estimatedCost: '£450.00',
  },
  {
    employeeId: 'emp001',
    type: 'exercise',
    description: 'Regular stretching breaks every 2 hours',
    status: 'in_progress',
    priority: 'medium',
    source: 'vida',
    createdBy: 'vida-system',
    dateCreated: '2024-01-10T09:15:00Z',
    dateUpdated: '2024-01-20T14:30:00Z',
  },
  {
    employeeId: 'emp002',
    type: 'behavioural',
    description: 'Improve posture during video calls',
    status: 'completed',
    priority: 'low',
    source: 'admin',
    createdBy: 'admin@company.com',
    dateCreated: '2024-01-05T08:00:00Z',
    dateUpdated: '2024-01-25T16:45:00Z',
    dateCompleted: '2024-01-25T16:45:00Z',
    notes: 'Employee has implemented posture reminders',
  },
  {
    employeeId: 'emp003',
    type: 'lifestyle',
    description: 'Ergonomic chair adjustment needed',
    status: 'pending',
    priority: 'medium',
    source: 'admin',
    createdBy: 'hr@company.com',
    dateCreated: '2024-01-22T11:20:00Z',
    dateUpdated: '2024-01-22T11:20:00Z',
    estimatedCost: '£200.00',
  },
  {
    employeeId: 'emp004',
    type: 'equipment',
    description: 'Monitor arm for dual screen setup',
    status: 'dismissed',
    priority: 'low',
    source: 'vida',
    createdBy: 'vida-system',
    dateCreated: '2024-01-12T13:10:00Z',
    dateUpdated: '2024-01-28T10:15:00Z',
    notes: 'Employee declined - prefers current setup',
  },
  {
    employeeId: 'emp005',
    type: 'exercise',
    description: 'Desk exercises for neck and shoulders',
    status: 'in_progress',
    priority: 'medium',
    source: 'vida',
    createdBy: 'vida-system',
    dateCreated: '2024-01-18T15:30:00Z',
    dateUpdated: '2024-01-25T09:45:00Z',
  },
];
